### ISSUE TITLE
Rewrite build-script in Go

### ISSUE THREAD

**Issue by Luzifer** [Luzifer/gobuilder#62]
## Benefits
- No more shell script to keep clean and up to date with latest features
- Removing the extra go tool to read the `.gobuilder.yml` and make their values available in bash
- Lesser number of modifications on build images
## TODOs
- [ ] Rewrite current state in Go
- Add feature-flips
  - [ ] En/disable `godep` handling (fixes #61)
  - [ ] Specialize `$GOPATH` for vendor directory handling
- [ ] Make new tool download all external binaries from GoBuilder (godep, s3sync, …)
- [ ] Make the container sync the assets itself instead of letting the build-starter do this
- [ ] Ensure builds without tags / branches are aborted immediately (fixes #59)
- [ ] Pack assets in ZIP and TGZ (refs #63)
